# Generated by Django 2.0.2 on 2018-03-28 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subquestion',
            name='choice',
        ),
        migrations.AddField(
            model_name='subquestion',
            name='choice',
            field=models.OneToOneField(default='4', on_delete=django.db.models.deletion.CASCADE, to='questions.Choice'),
            preserve_default=False,
        ),
    ]
