# Generated by Django 2.0.2 on 2018-03-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20180328_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='subquestion',
            name='sub_choice',
            field=models.ManyToManyField(related_name='sub_question_choice', to='questions.Choice'),
        ),
    ]
