# Generated by Django 2.0.2 on 2018-03-28 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_subquestion_sub_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subquestion',
            old_name='choice',
            new_name='outcome',
        ),
    ]
