# Generated by Django 2.0.2 on 2018-03-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20180328_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subquestion',
            name='outcome',
        ),
        migrations.AddField(
            model_name='subquestion',
            name='outcome',
            field=models.ManyToManyField(blank=True, to='polls.Choice'),
        ),
    ]
