# Generated by Django 2.0.2 on 2018-03-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_choice_compliance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subquestion',
            name='outcome',
        ),
    ]
