# Generated by Django 2.0.2 on 2018-03-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_remove_subquestion_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='subquestion',
            name='outcome',
            field=models.CharField(choices=[('1', 'Compliant'), ('2', 'Partially Compliant 75%'), ('3', 'Partially Compliant 50%'), ('4', 'Partially Compliant 25%'), ('5', 'Non-Compliant'), ('6', 'Not Applicable')], default='Not Applicable', max_length=200),
            preserve_default=False,
        ),
    ]
