# Generated by Django 2.0.2 on 2018-03-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_subquestion_outcome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subquestion',
            name='sub_choice',
        ),
        migrations.AddField(
            model_name='subquestion',
            name='sub_choice',
            field=models.CharField(default='Yes', max_length=200),
            preserve_default=False,
        ),
    ]
