# Generated by Django 2.0.2 on 2018-03-29 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_auto_20180329_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('compliance_status', models.CharField(choices=[('1', 'Compliant'), ('2', 'Partially Compliant 75%'), ('3', 'Partially Compliant 50%'), ('4', 'Partially Compliant 25%'), ('5', 'Non-Compliant'), ('6', 'Not Applicable')], max_length=200)),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='subquestion',
            name='sub_choice',
        ),
        migrations.AddField(
            model_name='subquestion',
            name='sub_choice',
            field=models.CharField(default='Yes', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.SubQuestion'),
        ),
    ]
