# Generated by Django 2.0.2 on 2018-03-29 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_auto_20180329_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subquestion',
            name='sub_choice',
        ),
        migrations.AddField(
            model_name='subchoice',
            name='sub_question',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, to='questions.SubQuestion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
    ]
