# Generated by Django 2.0.2 on 2018-04-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_auto_20180329_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='comment',
            field=models.TextField(blank=True, max_length=50, verbose_name='Comment'),
        ),
    ]
