# Generated by Django 2.0.2 on 2018-04-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_question_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='comment',
            field=models.TextField(blank=True, max_length=500, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Publish Date'),
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Publish Date'),
        ),
    ]
