# Generated by Django 2.0.2 on 2018-04-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_auto_20180402_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='compliance/%Y/%m/$D/'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='compliance_image/%Y/%m/$D/'),
        ),
    ]
