# Generated by Django 2.0.2 on 2018-04-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_auto_20180403_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='frequency',
            field=models.CharField(choices=[('1', 'Hourly'), ('2', 'Daily'), ('3', 'Weekly'), ('4', 'Monthly'), ('5', 'Yearly')], default='Once', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='compliance/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='compliance_image/%Y/%m/%D/'),
        ),
    ]
