# Generated by Django 2.0.2 on 2018-04-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_auto_20180409_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='action',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='choice',
            name='comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='frequency',
            field=models.CharField(choices=[('1', 'Once'), ('2', 'Hourly'), ('3', 'Daily'), ('4', 'Weekly'), ('5', 'Monthly'), ('6', 'Yearly')], max_length=200),
        ),
    ]
