# Generated by Django 2.0.2 on 2018-04-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_auto_20180409_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='subchoice',
            name='action',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subchoice',
            name='comment',
            field=models.BooleanField(default=False),
        ),
    ]
