# Generated by Django 2.0.2 on 2018-04-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_auto_20180409_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='comment',
        ),
        migrations.AddField(
            model_name='question',
            name='information',
            field=models.TextField(blank=True, max_length=500, verbose_name='Information'),
        ),
        migrations.AlterField(
            model_name='question',
            name='frequency',
            field=models.CharField(choices=[('1', 'Once'), ('2', 'Hourly'), ('3', 'Daily'), ('4', 'Weekly'), ('5', 'Monthly'), ('6', 'Yearly')], default='Once', max_length=200),
        ),
    ]
