# Generated by Django 2.0.2 on 2018-04-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0023_auto_20180409_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='footnote',
            field=models.TextField(blank=True, max_length=500, verbose_name='Footnote'),
        ),
    ]
