# Generated by Django 2.0.2 on 2018-04-24 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0024_question_footnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
