# Generated by Django 2.0.2 on 2018-04-25 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0025_question_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='weight',
            new_name='score',
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ManyToManyField(related_name='Assign_To', to=settings.AUTH_USER_MODEL),
        ),
    ]
