# Generated by Django 2.0.2 on 2018-04-25 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0026_auto_20180425_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subchoice',
            old_name='weight',
            new_name='score',
        ),
    ]
