# Generated by Django 2.0.2 on 2018-04-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0027_auto_20180425_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
