# Generated by Django 2.0.2 on 2018-05-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0029_auto_20180507_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='question',
        ),
        migrations.AddField(
            model_name='audit',
            name='question',
            field=models.ManyToManyField(blank=True, null=True, to='questions.Question'),
        ),
    ]
